name: fay
channels:
  - defaults
dependencies:
  - python=3.10
  - requests
  - numpy
  - pyaudio=0.2.11
  - websockets=10.2
  - ws4py=0.5.1
  - pyqt=5.15.6
  - flask=3.0.0
  - openpyxl=3.0.9
  - flask-cors=3.0.10
  - pyqtwebengine=5.15.5
  - eyed3=0.9.6
  - websocket-client
  - azure-cognitiveservices-speech
  - aliyun-python-sdk-core
  - simhash
  - pytz
  - gevent=22.10.1
  - edge-tts=6.1.3
  - ultralytics=8.0.2
  - pydub
  - cemotion
  - langchain=0.0.336
  - chromadb
  - tenacity=8.2.3
  - pygame
  - scipy
  - pip
